### ISSUE TITLE
How to solve this?

### ISSUE THREAD

**Issue by MarsZhu** [robeio/robe-ajax#1]
``
![8207133368 chatroom_1484550329503_15](https://cloud.githubusercontent.com/assets/5705504/21973711/9b70864c-dbfd-11e6-8498-9141bcbd878d.png)
![8207133368 chatroom_1484550329396_72](https://cloud.githubusercontent.com/assets/5705504/21973728/b4654228-dbfd-11e6-99c4-4c301a16cf83.png)

**Comment by kbukum** [comment]
Hello @MarsZhu 

As I see you are using renerator-runtime to call ajax functions. You are trying to evaluation the coming response but I haven't any idea about the response. I think the problem is not about the ajax function probably  the error getting from the evaluation of response (eval('(' + data + ')')).

**Comment by MarsZhu** [comment]
Thank you ! Now, I knew it is the json problem from web server!

**Comment by kbukum** [comment]
You are welcome.
